use_frameworks!

platform :ios, '10.0'

target 'IQKeyboardToolbar_Example' do
  pod 'IQKeyboardToolbar', :path => '../'

  target 'IQKeyboardToolbar_Tests' do
    inherit! :search_paths

    
  end
end
